name: Lint
on:
  push:
    branches:
      - '**'
    paths:
      - '**.php'
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
    paths:
      - '**.php'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: Run PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # User PHP 7.4 here for compatibility with the WordPress codesniffer rules.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - uses: technote-space/get-diff-action@v6 # repo is archived.
        with:
          SUFFIX_FILTER: .php

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer vendor directory
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --no-progress --optimize-autoloader --prefer-dist

      - name: Fix auto-fixable PHP Code Standards Violations
        continue-on-error: true
        run: vendor/bin/phpcbf --standard=phpcs.xml

      - name: Commit PHPCBF changes on main
        if: ${{ github.ref == 'refs/heads/main' }} # only commit on main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 PHPCBF"
          commit_options: ""
        env:
          GITHUB_TOKEN: "${{ github.token }}"

      - name: Detecting PHP Code Standards Violations
        run: vendor/bin/phpcs --standard=phpcs.xml -s ${{ env.GIT_DIFF }} --report=checkstyle | cs2pr
        if: "!! env.GIT_DIFF"
