name: Trigger Satis Build

on:
  release:
    types:
      - created

env:
  VERSION: ${GITHUB_REF#refs/tags/*}

jobs:
  webhook:
    name: Send Webhook
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate version number
        if: ${{ (github.repository == 'newfold-labs/wp-module-data') && (github.event.release.prerelease == false) }}
        run: |
          taggedVersion=${{ env.VERSION }}
          moduleVersion=`grep "NFD_DATA_MODULE_VERSION" bootstrap.php | grep -Eo "[0-9\.]*"`
          echo "Tagged version: $taggedVersion"
          echo "Module version: $moduleVersion"
          [[ "$taggedVersion" == "$moduleVersion" ]] || exit 1

      - name: Set Package
        id: package
        env:
          REPO: ${{ github.repository }}
        run: echo ::set-output name=PACKAGE::${REPO##*/}

      - name: Set Version
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WEBHOOK_TOKEN }}
          repository: newfold-labs/satis
          event-type: 'satis-build'
          client-payload: >-
            {
              "vendor": "${{ github.repository_owner }}",
              "package": "${{ steps.package.outputs.PACKAGE }}",
              "version": "${{ steps.tag.outputs.VERSION }}"
            }
